### ISSUE TITLE
Do not print the types in the operand list

### ISSUE THREAD

**Issue by tobiasgrosser** [xdslproject/xdsl#66] opened 2022-03-15 09:07 UTC
Printing and requiring types after an operand use makes the IR unnecessarily verbose and hard to read. MLIR does not do this either. Hence, I wonder, should we maybe just not do this?

**Comment by Dinistro** [comment] 2022-03-24 12:54
This seems to be a duplicate of #27

**Closed by Dinistro** 2022-03-24 12:54 UTC
